### PR TITLE
Interactive list

### PR DESCRIPTION
**Pull request by Salimer**
## What does this PR do?

This PR is raised to implement the following features: 👍 :

- [x] Add a new JavaScript file and import it as a module.
- [x] Add event listener to the checkbox (change).
- [x] Update items object's value for completed key upon user actions.
- [x] Implement a function for the "Clear all completed" button.
- [x] Store the updated array of items in local storage, so the user gets the correct list of values after the page reloads.

## Description of the completed tasks 🙌

- [x] Update Read me file 
- [x] Add the HTML for the structure. 
- [x] Add the CSS file for the styling.
- [x] Use the linter tool that analyzes my source code to flag programming errors, bugs, stylistic errors, and suspicious constructs. 💯

### CODE REVIEW

**Review by AdnanOlarmmi — APPROVED** [review]
Hi @Salimer,

This is Adnan Is-haq, your beloved code reviewer, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Approved office man

## Highlights
- Clean and modular code base, keep up the great work.
- Simple but yet outstanding UI design.

mobile


## Optional suggestions
_Check the comments under the review._

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Salimer** [comment]
Many thanks for the amazing review @AdnanOlarmmi 🥳

**Comment by AdnanOlarmmi** [comment]
You're welcome @Salimer, forgot to add the working live demo, now I have. Have a nice one. See ya

**Comment by Salimer** [comment]
Thank you @AdnanOlarmmi I liked your live demo. Can I add it on my readme file please? 🙈

**Pull request merged**
